### ISSUE TITLE
Error in run.py

### ISSUE THREAD

**Issue by ratul619** [lpentecost/NVMExplorer#1]
Hi , 

I am running NVMexplorer , but facing below issue : 

ratul619@ratul619-VirtualBox:~/IIT_study_VM/NVMExplorer$ python3.8   run.py config/main_dnn_study.json 
Successfully Loaded Config File
Traceback (most recent call last):
  File "run.py", line 192, in <module>
    data_df = load_spreadsheet_data(_cell_type, output_path)
  File "run.py", line 45, in load_spreadsheet_data
    temp_df.replace('', np.nan, inplace = True) # fill empty cells with NAN to make processing easier
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 4272, in replace
    return super().replace(
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 6626, in replace
    self._consolidate_inplace()
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 5252, in _consolidate_inplace
    self._protect_consolidate(f)
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 5240, in _protect_consolidate
    blocks_before = len(self._data.blocks)
AttributeError: 'NoneType' object has no attribute 'blocks'

Thanks

**Comment by alexanderhankin** [comment]
Hi @ratul619 

Sorry for the delay -- 

Can you please let me know what version of pandas you are using?
